source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YUTagView_Example', :exclusive => true do
  pod "YUTagView", :path => "../"
end

target 'YUTagView_Tests', :exclusive => true do
  pod "YUTagView", :path => "../"

  pod 'FBSnapshotTestCase'
end
